-- Create the review table
CREATE TABLE IF NOT EXISTS public.review (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text TEXT NOT NULL,
    review_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    inv_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id)
);